theme                    : jekyll-theme-minimal

# site settings
locale                   : "en-US"
title                    : "Ruobin Gong"
title_separator          : "-"
name                     : &name "Ruobin Gong"
description              : &description "Assistant Professor of Statistics, Rutgers University"
url                      : https://RuobinGong.github.io 

# Site Author
author:
  name             : "Ruobin Gong"
  bio              : "Statistician"
  location         : "Location"
  employer         : "Rutgers University"
  pubmed           : "https://www.ncbi.nlm.nih.gov/pubmed/?term=john+snow"
  googlescholar    : "http://yourfullgooglescholarurl.com"
