theme: jekyll-theme-minimal

# site settings

locale                   : "en-US"
title                    : "Ruobin Gong / Personal Webpage"
title_separator          : "-"
name                     : &name "Ruobin Gong"
description              : &description "Statistician"
url                      : https://RuobinGong.github.io 
